services:

    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        extra_hosts:
            - host.docker.internal:host-gateway
            - front-app.local.com.br:host-gateway
        image: nilbertooliveira/php:8-fpm-alpine
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            PHP_IDE_CONFIG: "serverName=docker"
            COMPOSER_MEMORY_LIMIT: -1
            COMPOSER_ALLOW_SUPERUSER: 1
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            app-network:
                ipv4_address: 172.27.0.2
        cpus: 0.2
        mem_limit: 300m

    webserver:
        image: 'bitnami/nginx:latest'
        container_name: webserver
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        ports:
            - "8081:80"
        environment:
            - VIRTUAL_HOST=app.local.com.br
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf
        extra_hosts:
            - host.docker.internal:host-gateway
            - front-app.local.com.br:host-gateway
        networks:
            app-network:
                ipv4_address: 172.27.0.3
        cpus: 0.2
        mem_limit: 100m

    db:
        image: bitnami/mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_DATABASE: app
        volumes:
            - mysql-data:/bitnami/mysql/data
        ports:
            - "3306:3306"
        networks:
            app-network:
                ipv4_address: 172.27.0.5
        cpus: 0.2
        mem_limit: 100m

    nginx-proxy:
        container_name: 'nginx-proxy'
        image: jwilder/nginx-proxy
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./docker/nginx/nginx-proxy/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/nginx-proxy/conf.d/vhost.d:/etc/nginx/vhost.d/
        ports:
            - "80:80"
        networks:
            app-network:
                ipv4_address: 172.27.0.98
        cpus: 0.2
        mem_limit: 50m

    redis:
        image: 'bitnami/redis:latest'
        container_name: redis
        restart: unless-stopped
        tty: true
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - redis-data:/bitnami
        networks:
            app-network:
                ipv4_address: 172.27.0.90
        ports:
            - "6379:6379"
        cpus: 0.2
        mem_limit: 100m


networks:
    app-network:
        external: true

volumes:
    redis-data:
    mysql-data:

